export const SET_PERSONAL_DETAILS = 'SET_PERSONAL_DETAILS';
export const SET_BUSINESS_DETAILS = 'SET_BUSINESS_DETAILS';
export const SET_BVN_DETAILS = 'SET_BVN_DETAILS';
export const ADD_BRANCH = 'ADD_BRANCH';
export const REMOVE_BRANCH = 'REMOVE_BRANCH';
export const SET_BRANCH_INFO = 'SET_BRANCH_INFO';
export const SET_DOCUMENT = 'SET_DOCUMENT';
export const SET_DOCUMENT_DATA_URL = 'SET_DOCUMENT_DATA_URL';